# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.22)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS hello::hello hello::bye)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target hello::hello
add_library(hello::hello STATIC IMPORTED)

set_target_properties(hello::hello PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cmake_learning/cmake_export/hello/./include"
)

# Create imported target hello::bye
add_library(hello::bye STATIC IMPORTED)

set_target_properties(hello::bye PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cmake_learning/cmake_export/hello/./include"
)

# Import target "hello::hello" for configuration "Debug"
set_property(TARGET hello::hello APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hello::hello PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/cmake_learning/cmake_export/hello/build/Debug/hello.lib"
  )

# Import target "hello::bye" for configuration "Debug"
set_property(TARGET hello::bye APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hello::bye PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/cmake_learning/cmake_export/hello/build/Debug/bye.lib"
  )

# Import target "hello::hello" for configuration "Release"
set_property(TARGET hello::hello APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hello::hello PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/cmake_learning/cmake_export/hello/build/Release/hello.lib"
  )

# Import target "hello::bye" for configuration "Release"
set_property(TARGET hello::bye APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hello::bye PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/cmake_learning/cmake_export/hello/build/Release/bye.lib"
  )

# Import target "hello::hello" for configuration "MinSizeRel"
set_property(TARGET hello::hello APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hello::hello PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/cmake_learning/cmake_export/hello/build/MinSizeRel/hello.lib"
  )

# Import target "hello::bye" for configuration "MinSizeRel"
set_property(TARGET hello::bye APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hello::bye PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/cmake_learning/cmake_export/hello/build/MinSizeRel/bye.lib"
  )

# Import target "hello::hello" for configuration "RelWithDebInfo"
set_property(TARGET hello::hello APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hello::hello PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cmake_learning/cmake_export/hello/build/RelWithDebInfo/hello.lib"
  )

# Import target "hello::bye" for configuration "RelWithDebInfo"
set_property(TARGET hello::bye APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hello::bye PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cmake_learning/cmake_export/hello/build/RelWithDebInfo/bye.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
